export const categoryColors: Record<string, string> = {
  biological: '#4A5D4E',
  chemical: '#3E5055',
  economic: '#8B7355',
  electrochemical: '#546E7A',
  electrical: '#546E7A',
  environmental: '#3E5244',
  materials: '#5D4E5D',
  'monitoring-control': '#998B5C',
  monitoring: '#998B5C',
  operational: '#4A5768',
  performance: '#6B3E3E',
  'reactor-design': '#8B5A3C',
  physical: '#8B5A3C',
  'safety-regulatory': '#7C7F82',
  safety: '#7C7F82',
  'application-specific': '#5C7A5C',
  'emerging-technology': '#A67C52',
  'integration-scaling': '#5C6B7A',
};

export const categoryLabels: Record<string, string> = {
  biological: 'Biological',
  chemical: 'Chemical',
  economic: 'Economic',
  electrochemical: 'Electrochemical',
  electrical: 'Electrical',
  environmental: 'Environmental',
  materials: 'Materials',
  'monitoring-control': 'Monitoring & Control',
  monitoring: 'Monitoring',
  operational: 'Operational',
  performance: 'Performance',
  'reactor-design': 'Reactor Design',
  physical: 'Physical',
  'safety-regulatory': 'Safety & Regulatory',
  safety: 'Safety',
  'application-specific': 'Application-Specific',
  'emerging-technology': 'Emerging Technology',
  'integration-scaling': 'Integration & Scaling',
};
