import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#f9f4ea',
        black: 'rgb(12 22 56 / 90%)',
        'mes-sage': '#4A5D4E',
        'mes-graphite': '#3E5055',
        'mes-brass': '#8B7355',
        'mes-burgundy': '#6B3E3E',
        'mes-labcoat': '#546E7A',
        'mes-paper': '#FAF8F5',
        'mes-steel': '#9E9B97',
        'mes-concrete': '#7C7F82',
        'mes-bakelite': '#2E2925',
        'mes-instrument': '#D4CFC7',
        'mes-glass': '#E8E6E3',
        'mes-geobacter': '#5D4E5D',
        'mes-shewanella': '#998B5C',
        'mes-algae': '#3E5244',
        'mes-iron-bacteria': '#8B5A3C',
        'mes-consortium': '#4A5768',
        'mes-optimal': '#5C7A5C',
        'mes-warning': '#A67C52',
        'mes-critical': '#8B4545',
        'mes-inactive': '#858585',
        'mes-info': '#5C6B7A',
        'mes-text-primary': '#1A1916',
        'mes-text-secondary': '#3E3C38',
        'mes-text-muted': '#6B6966',
        'mes-text-inverse': '#FAF8F5',
        'mes-text-link': '#546E7A',
        gray: {
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
          950: '#0a0a0a',
        },
      },
      fontFamily: {
        sans: [
          'DM Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
        mono: [
          'DM Mono',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
        serif: ['Crimson Text', 'Georgia', 'Times New Roman', 'serif'],
        display: ['Crimson Text', 'Georgia', 'serif'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
      },
      borderRadius: {
        none: '0',
        DEFAULT: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      boxShadow: {
        sm: '0 1px 3px rgba(46, 41, 37, 0.12)',
        DEFAULT: '0 2px 6px rgba(46, 41, 37, 0.15)',
        md: '0 4px 12px rgba(46, 41, 37, 0.15)',
        lg: '0 8px 24px rgba(46, 41, 37, 0.20)',
        none: '0 0 #0000',
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-in': 'slideIn 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideIn: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
